global:
  scrape_interval:     10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'promtail'
    static_configs:
      - targets: ["promtail:9080"]
  
  - job_name: 'grafana'
    static_configs:
      - targets: ["grafana:3000"]
  
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'python-web-app'
    static_configs:
      - targets: ['python-web-app:8000']
  
  - job_name: 'golang-web-app'
    static_configs:
      - targets: ['python-web-app:8000']