# This is a basic workflow to help you get started with Actions

name: Python Web-App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_python  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.12' 
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Linter 
      run: |
        pip install pylint
        pylint app.py
    - name: UnitTests
      run: | 
        python -m unittest unit_test/app_test.py -v 
      
    - name: Login to Docker
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: docker build 
      run: | 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-web-app:latest .
      
    - name: docker push 
      run: | 
        docker push ${{ secrets.DOCKER_USERNAME }}/python-web-app:latest 